# Generated by Django 5.2.3 on 2025-06-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('usuarionormal', 'Usuario Normal')], max_length=30),
        ),
    ]
